import QRCode from "qrcode";
import { cn } from "@/lib/cn";

interface QrCodeProps {
  value: string;
  /** Accessible description, e.g. "Código QR de la sesión para docentes". */
  label: string;
  className?: string;
}

/**
 * QR code rendered on the server as inline SVG: no client JavaScript, crisp at any size.
 * Dark modules on white, the most reliable combination for phone cameras.
 */
export async function QrCode({ value, label, className }: QrCodeProps) {
  const svg = await QRCode.toString(value, {
    type: "svg",
    margin: 1,
    errorCorrectionLevel: "M",
    color: { dark: "#0F1F2C", light: "#FFFFFF" },
  });

  return (
    <span
      role="img"
      aria-label={label}
      className={cn("block overflow-hidden rounded-lg bg-white [&>svg]:h-full [&>svg]:w-full", className)}
      // Generated by the qrcode library from our own URL, never from user input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
